lang1:
    name:
        short: en
        full: English
    talk: false
    hint: 0
    dynamic: False
lang2:
    name:
        short: es
        full: Spanish
    talk: true
    hint: 1
    dynamic: True
redo: true
path: ..\..\SpanishVocab\Design
num: 12
record: true
