providers:
    _default: "multifile"
    _common:
        lang1:
            short: en
            full: English
        lang2:
            short: it
            full: Italian
    singlefile:
        filepath: ..\..\ItalianVocab\Design\adjectives.txt
    multifile:
        filepaths:
            - ..\..\ItalianVocab\Design\nouns-food.txt
            - ..\..\ItalianVocab\Design\nouns-shopping.txt
modes:
    _common:
        reviewnum: 12
        shuffle: true
    listen:
        reviewnum: 24
    translate:
        reviewnum: 10
