lang1:
    name:
        short: en
        full: English
    talk: false
    hint: 0
lang2:
    name:
        short: it
        full: Italian
    talk: true
    hint: 2
redo: false
path: ..\..\ItalianVocab\Design
num: 10
